name: Set Environment Variable
on: [workflow_dispatch]
jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
     - name: My Step
       id: my-step
       run: echo "Hello from workflow!"
    # steps:
    #  - name: Install Dependencies
    #    run: yarn install
    #    env:
    #      API_KEY: ${{ secrets.API_KEY }}