name: Set Environment Variable
on: [push]
jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
     - name: Install Dependencies
       run: yarn install
       env:
         API_KEY: ${{ secrets.API_KEY }}