name: Set Environment Variable
on: [workflow_dispatch]
jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
     - name: My Step
       id: read_json
      #  run: echo "::set-output name=my-output::Hello, World!"
       run: |
         content=$(cat ./path/to/package.json)
        echo "::set-output name=packageJson::$content"
    # steps:
    #  - name: Install Dependencies
    #    run: yarn install
    #    env:
    #      API_KEY: ${{ secrets.API_KEY }}