name: Flask Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
         mysql:
          image: mysql:5.7
          ports:
           - 3306:3306
          options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install pip Dependencies
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
         cache: 'pip'

      - run: |
            pip install -r requirements.txt

  
      - name: Set up ngrok
        run: sudo snap install ngrok --devmode && ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: forward port to web
        run: ngrok http --domain=key-grizzly-directly.ngrok-free.app 5000 &
      
      

      - name: Wait for MySQL to be ready
        
        run: |
          while ! mysqladmin ping --silent; do
            sleep 1
          done
      
      - name: Set up MySQL Database
        run: |
          mysql -u user -p password -e "CREATE DATABASE mydb;"


      - name: Starting application
        run: | 
            sudo service mysql start && \
            mysql -u user -p password mydb -e \
             "CREATE TABLE users (  \
              id INT NOT NULL AUTO_INCREMENT,  \
              first_name VARCHAR(20), \
              middle_name VARCHAR(20), \
              last_name VARCHAR(20), \
              age INT, \
              phone BIGINT, \
              email VARCHAR(30), \
              country VARCHAR(5), \
              username VARCHAR(30), \
              passhash VARCHAR(180), \
              salt VARCHAR(100), \
              PRIMARY KEY (id) );" && \
             python app.py \
            'localhost' \
            '3306' \
            'user' \
            'password' \
            'mydb' &
            
      - run: sleep 600
 

  






       
