name: Flask Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2 

      # - name: Install pip Dependencies
      #   uses: actions/setup-python@v4
      #   with:
      #    python-version: '3.10'
      #    cache: 'pip'

      # - run: |
      #       pip install -r requirements.txt

  
      # - name: Set up ngrok
      #   run: sudo snap install ngrok --devmode && ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      # - name: forward port to web
      #   run: ngrok http --domain=key-grizzly-directly.ngrok-free.app 5000 &
      
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
            mysql-version: "8.0"
      - run: |
         
          mysql -u root mydb -e \
            "CREATE TABLE users (  \
              id INT NOT NULL AUTO_INCREMENT,  \
              first_name VARCHAR(20), \
              middle_name VARCHAR(20), \
              last_name VARCHAR(20), \
              age INT, \
              phone BIGINT, \
              email VARCHAR(30), \
              country VARCHAR(5), \
              username VARCHAR(30), \
              passhash VARCHAR(180), \
              salt VARCHAR(100), \
              PRIMARY KEY (id) );" && \
          mysql -u root mydb -e "desc users;"

      - name: Starting application
        run: | 
            python app.py \
            'localhost' \
            '3306' \
            'user' \
            'password' \
            'mydb' &
            
      # - run: sleep 600
 

  






       
