name: Flask Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
         cache: 'pip'

      - name: Install pip Dependencies
        run: |
            pip install -r requirements.txt

  
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
            mysql-version: "8.0"
      
      - name: Cache MySQL
        uses: actions/cache@v2
        with:
          path: /tmp/mydb.sql
          key: ${{ runner.os }}-mysql-${{ hashFiles('/tmp/mydb.sql') }}
          restore-keys: |
            ${{ runner.os }}-mysql-

      - run: |
          mysql -u root -p -e "CREATE DATABASE mydb;" && \
          mysql -u root mydb < /tmp/mydb.sql || mysql -u root -p mydb -e \
            "CREATE TABLE users (  \
              id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, \
              first_name VARCHAR(20), \
              middle_name VARCHAR(20), \
              last_name VARCHAR(20), \
              age INT, \
              phone BIGINT, \
              email VARCHAR(30), \
              country VARCHAR(5), \
              username VARCHAR(30), \
              passhash VARCHAR(180), \
              salt VARCHAR(100));" && \
          mysql -u root mydb -e "desc users;" && \
          mysql -u root mydb -e "SELECT * from users;"
          
      - name: Starting application
        run: | 
            python app.py \
            '127.0.0.1' \
            '3306' \
            'root' \
            '' \
            'mydb' &

      - name: Set up ngrok
        run: sudo snap install ngrok --devmode && ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: forward port to web
        run: ngrok http --domain=key-grizzly-directly.ngrok-free.app 5000 &

      - run: sleep 60

         
      - name: Trigger next workflow
        run: gh auth login --with-token <<<"${{ secrets.WORKFLOW_TOKEN }}" && gh workflow run workflow.yml
 
   






       
