name: Flask Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install pip Dependencies
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
         cache: 'pip'

      - run: |
            pip install -r requirements.txt

  
      - name: Set up ngrok
        run: sudo snap install ngrok --devmode && ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: forward port to web
        run: ngrok http --domain=key-grizzly-directly.ngrok-free.app 5000 &
      
      
      - name: Set up MySQL Database
        run: |
          sudo service mysql start && \
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpassword'; FLUSH PRIVILEGES;" &&\
          mysql -u root -prootpassword -e "CREATE DATABASE mydb;"
          # mysql -u root -prootpassword -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON mydb.* TO 'user'@'localhost'; "
          # mysql -u user -ppassword mydb -e \
          #    "CREATE TABLE users (  \
          #     id INT NOT NULL AUTO_INCREMENT,  \
          #     first_name VARCHAR(20), \
          #     middle_name VARCHAR(20), \
          #     last_name VARCHAR(20), \
          #     age INT, \
          #     phone BIGINT, \
          #     email VARCHAR(30), \
          #     country VARCHAR(5), \
          #     username VARCHAR(30), \
          #     passhash VARCHAR(180), \
          #     salt VARCHAR(100), \
          #     PRIMARY KEY (id) );"

      - name: Starting application
        run: | 
            python app.py \
            'localhost' \
            '3306' \
            'user' \
            'password' \
            'mydb' &
            
      - run: sleep 600
 

  






       
